<?php
/**
 * Copyright © 2017 SkyBox Checkout Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @codingStandardsIgnoreFile */

/**
 * SkyBox Checkout - Shopping cart template
 *
 * @var \Skybox\Checkout\Block\Scheckout\Totals $block
 */

if($block->isEnabled()) {    
?>
<div class="skbx-price">
    <?php if($block->getIntegrationType()==1){ ?>
        <div class="skbx-loader-subtotal"></div>
        <div align="right" class="international-checkout"></div>
    <?php }?>
        <div class="skybox-checkout-payment-btn action primary checkout"></div>
</div>

    <?php
    if($block->getIntegrationType()==1) {
    ?>

    <script>
        requirejs(['jquery'], function($) {
            $(document).ready(function() {
                $('#block-shipping').addClass('skbx-price-store');
                $('#cart-totals').addClass('skbx-price-store');
            });
        });
    </script>
<?php }
}?>